---
- hosts: app-server
  tasks:
    - name: copy file to remote host
      copy:
        src: /mnt/artefact/
        dest: /mnt/artefact/
        
    - name: Start application
      shell: java -jar /mnt/artefact/*.jar
