pipeline {
    agent any

    stages {
        stage('Git Pull ') {
            steps {
                git branch: 'main', url: 'https://github.com/spring-projects/spring-petclinic.git'   
            }
        }
        
        stage('Build') {
            steps {
                    sh "./mvnw package"
            }
            
        }
        stage('Unit Tests') {
            steps {
                    sh "./mvnw test"
            }
             post {
                success {
                    sh "mv target/*.jar /mnt/artefact"
                }
            }
        }
        stage('Deploy') {
            steps {
                    sh ".ansible-playbook -u centos /etc/ansible/deploy.yml  --extra-vars “app-server” -i hosts --private-key ~/.ssh/demo.pem
"
            }
            
        }
    }
}
