pipeline {
    agent any

    tools {
        
        maven "demo_maven_3.6.3"
    }

    stages {
        stage('Git Pull ') {
            steps {
                git branch: 'main', url: 'https://github.com/spring-projects/spring-petclinic.git'   
            }
        }
        
        stage('Build') {
            steps {
                    sh "./mvnw package"
            }
             post {
                success {
                    sh "mv target/*.jar /mnt/artefact"
                }
            }
        }
     
    }
}
